// Client/src/app/feature/components/trading/place-order/place-order.component.ts
import { NgClass } from '@angular/common';
import { Component, input, OnChanges, OnDestroy, OnInit, signal } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { Subscription } from 'rxjs';
import { OrderService } from '../../../services/order.service';
import { ToastService } from '../../../../shared/services/toast.service';
import { EventService } from '../../../services/event.service';
import { SocketService } from '../../../../core/services/socket.service';

interface Form {
  price: FormControl<number | null>;
  quantity: FormControl<number | null>;
}

@Component({
  selector: 'app-place-order',
  imports: [
    NgClass,
    ReactiveFormsModule
  ],
  templateUrl: './place-order.component.html',
  styleUrl: './place-order.component.css'
})
export class PlaceOrderComponent implements OnInit, OnChanges, OnDestroy {
  eventId = input.required<string>();
  private subscription = new Subscription();
  form: FormGroup<Form> = new FormGroup<Form>({
    price: new FormControl(null, [ Validators.required ]),
    quantity: new FormControl(null, [ Validators.required ]),
  });
  isRunning = signal<boolean>(false);

  constructor(
    private event: EventService,
    private order: OrderService,
    private toast: ToastService,
    private socket: SocketService
  ){}
  
  ngOnInit(): void {
    this.socket.onEventStart(() => {
      this.isRunning.set(true);
    });
    this.socket.onEventEnd(() => {
      this.isRunning.set(false);
    });
  }

  ngOnChanges() {
    if (this.eventId()){
      this.subscription.add(
        this.event.isRunning(this.eventId())
        .subscribe(({ isRunning }) => {
          this.isRunning.set(isRunning);
        })
      );
    }
  }

  placeOrder(side: 'bid' | 'ask') {
    this.order.placeOrder(
      this.eventId(),
      this.form.controls['price'].value!,
      this.form.controls['quantity'].value!,
      side
    )
    .subscribe(({ message }) => {
      this.toast.info(message);
      this.form.reset();
    });
  }

  disabled() {
    return this.form.invalid || !this.isRunning();
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }
}

<div>
    <div class="flex justify-between gap-5">
        <div class="flex flex-col gap-1">
            <label htmlFor='price'>Price</label>
            <input 
                id="price" 
                type="number"
                [formControl]="form.controls['price']" 
                class="w-full py-2 px-3 text-black rounded-sm outline-none" 
            />
        </div>
        <div class="flex flex-col gap-1">
            <label htmlFor='quantity'>Quantity</label>
            <input 
                id="quantity" 
                type="number" 
                [formControl]="form.controls['quantity']" 
                class="w-full py-2 px-3 text-black rounded-sm outline-none"
            />
        </div>
    </div>
    <div class="flex justify-between gap-5 mt-5">
        <button 
            class="rounded-sm w-full py-2 bg-white text-black text-[12px]"
            [ngClass]="{
                'bg-secondary cursor-not-allowed': disabled()
            }"
            [disabled]="disabled()"
            (click)="placeOrder('bid')"
        >
            Buy
        </button>
        <button 
            class="rounded-sm w-full py-2 bg-white text-black text-[12px]"
            [ngClass]="{
                'bg-secondary cursor-not-allowed': disabled()
            }"
            [disabled]="disabled()"
            (click)="placeOrder('ask')"
        >
            Sell
        </button>
    </div>
</div>

// Client/src/pages/PlaceOrder.tsx
import { useEffect, useRef, useState, type ChangeEvent } from "react";
import { onEventEnd, onEventStart } from "../lib/socket";
import api from "../api/axios";

interface Order {
    price: number;
    quantity: number;
};

export default function PlaceOrder({eventId}: { eventId: string }) {
    const [order, setOrder] = useState<Order>({
        price: 0,
        quantity: 0
    });
    const [isRunning, setIsRunning] = useState(false);
    const disabled = isRunning ? !order.price && !order.quantity : true;
    const priceInputRef = useRef<HTMLInputElement>(null);
    const quantityInputRef = useRef<HTMLInputElement>(null);
    
    useEffect(() => {
        api.get<{ isRunning: boolean }>('/event/isRunning', {
            params: {
                eventId
            }
        })
        .then(({data}) => {
            setIsRunning(data.isRunning);
        })
        .catch(error => {
            console.log(error);
        });

        onEventStart(() => {
            setIsRunning(true);
        });
        onEventEnd(() => {
            setIsRunning(false);
        });
    }, []);

    function placeOrder(side: 'bid' | 'ask'){
        api.post<{ quantity: number }>('/order', {
            eventId,
            side,
            ...order
        })
        .then(({data}) => {
            setOrder({
                price: 0,
                quantity: 0
            });
            if (priceInputRef.current) {
                priceInputRef.current.value = '';
            }
            if (quantityInputRef.current) {
                quantityInputRef.current.value = '';
            }
        })
        .catch(error => {
            console.log(error);
        });
    }

    function handleInputChange(event: ChangeEvent<HTMLInputElement>) {
        setOrder({
            ...order,
            [event.target.id]: Number(event.target.value)
        });
    }

    return (
        <div>
            <div className="flex justify-between gap-5">
                <div className="flex flex-col gap-1">
                    <label htmlFor='price'>Price</label>
                    <input 
                        id="price" 
                        type="number" 
                        className="w-full py-2 px-3 text-black rounded-sm outline-none" 
                        ref={priceInputRef}
                        onChange={handleInputChange}
                    />
                </div>
                <div className="flex flex-col gap-1">
                    <label htmlFor='quantity'>Quantity</label>
                    <input 
                        id="quantity" 
                        type="number" 
                        className="w-full py-2 px-3 text-black rounded-sm outline-none"
                        ref={quantityInputRef}
                        onChange={handleInputChange}
                    />
                </div>
            </div>
            <div className="flex justify-between gap-5 mt-5">
                <button 
                    className={`rounded-sm w-full py-2 bg-white text-black text-[12px] ${disabled && 'bg-secondary'}`}
                    disabled={disabled}
                    onClick={() => placeOrder('bid')}
                >
                    Buy
                </button>
                <button 
                    className={`rounded-sm w-full py-2 bg-white text-black text-[12px] ${disabled && 'bg-secondary'}`}
                    disabled={disabled}
                    onClick={() => placeOrder('ask')}
                >
                    Sell
                </button>
            </div>
        </div>
    );
}
