// Client/src/pages/OrderBook.tsx
import { useEffect, useState } from "react";
import { onEventEnd, onEventStart, onOrderBook } from "../lib/socket";
import api from "../api/axios";

type OrderBook = {
    [price: number]: {
        quantity: number,
        side: 'bid' | 'ask'
    }
};

type OrderBookArr = [string, {
    quantity: number;
    side: "bid" | "ask";
}][];

export default function OrderBook() {
    const [orderBook, setOrderBook] = useState<OrderBookArr | null>(null);
    
    useEffect(() => {
        onOrderBook((orderBook: OrderBook) => {
            const orderBookArr = Array.from(Object.entries(orderBook));
            setOrderBook(orderBookArr);
        });
    }, []);

    return (
        <div className="mt-5">
            <div className="text-[12px] rounded-md w-full">
                <table className="w-full">
                    <thead>
                        <tr>
                            <td className="px-2 py-1">Price</td>
                            <td className="text-center px-2 py-1">Qty.</td>
                            <td className="text-end px-2 py-1">Type</td>
                        </tr>
                    </thead>
                    <tbody>
                        {orderBook && orderBook.map((order) => (
                            <tr key={order[0]} className={`${order[1].side === 'bid' ? 'bg-[#2962FF]' : 'bg-[#9928d1]'} text-white`}>
                                <td className="px-2 py-1">
                                    {order[0]}
                                </td>
                                <td className="text-center px-2 py-1">
                                    {order[1].quantity}
                                </td>
                                <td className="text-end px-2 py-1">
                                    {order[1].side}
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
}

// Client/src/app/feature/components/trading/order-book/order-book.component.ts
import { Component, input, OnDestroy, OnInit, signal } from '@angular/core';
import { Subscription } from 'rxjs';
import { SocketService } from '../../../../core/services/socket.service';
import { OrderBook, OrderBookArr } from '../../../../shared/interface/interface';

@Component({
  selector: 'app-order-book',
  imports: [],
  templateUrl: './order-book.component.html',
  styleUrl: './order-book.component.css'
})
export class OrderBookComponent implements OnInit, OnDestroy {
  eventId = input.required<string>();
  private subscription = new Subscription();
  orderBook = signal<OrderBookArr | null>(null);

  constructor(
    private socket: SocketService
  ) {}

  ngOnInit(): void {
    this.socket.emitOrderBookRequest(this.eventId());

    this.socket.onOrderBook((orderBook: OrderBook) => {
      const orderBookArr = Array.from(Object.entries(orderBook));
      this.orderBook.set(orderBookArr);
    });
    
    this.socket.onEventEnd(() => {
      this.orderBook.set([]);
    });
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }
}

<div class="mt-5">
    <div class="text-[12px] rounded-md w-full">
        <table class="w-full">
            <thead>
                <tr>
                    <td class="px-2 py-1">Price</td>
                    <td class="text-center px-2 py-1">Qty.</td>
                    <td class="text-end px-2 py-1">Type</td>
                </tr>
            </thead>
            <tbody>
                @for (order of orderBook(); track order[0]) {
                    <tr
                        [class]="'text-white ' + order[1].side === 'bid' ? 'bg-[#2962FF]' : 'bg-[#9928d1]'"
                    >
                        <td class="px-2 py-1">
                            {{ order[0] }}
                        </td>
                        <td class="text-center px-2 py-1">
                            {{ order[1].quantity }}
                        </td>
                        <td class="text-end px-2 py-1">
                            {{ order[1].side }}
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
