// Client/src/components/Chart.tsx

import { AreaSeries, createChart, ColorType } from 'lightweight-charts';
import type { Time } from 'lightweight-charts';
import { useEffect, useRef } from 'react';

interface DataPoint {
  time: Time;
  value: number;
}

interface Props {
  data: DataPoint[],
  colors?: {
    backgroundColor?: string;
    lineColor?: string;
    textColor?: string;
    areaTopColor?: string;
    areaBottomColor?: string;
  };
};

export const Chart: React.FC<Props> = ({
  data,
  colors: {
    backgroundColor = '#0a0b0b',
    lineColor = '#2962FF',
    textColor = 'white',
    areaTopColor = '#2962FF',
    areaBottomColor = 'rgba(41, 98, 255, 0.28)',
  } = {},
}) => {
  const chartContainerRef = useRef<HTMLDivElement>(null);

  useEffect(
      () => {
          const handleResize = () => {
              chart.applyOptions({ width: chartContainerRef.current!.clientWidth });
          };

          const chart = createChart(chartContainerRef.current!, {
              layout: {
                  background: { type: ColorType.Solid, color: backgroundColor },
                  textColor,
              },
              width: chartContainerRef.current!.clientWidth,
              height: 300,
              grid: {
                vertLines: {
                  color: 'transparent',
                },
                horzLines: {
                  color: 'transparent',
                },
              },
          });
          chart.timeScale().fitContent();
          chart.timeScale().applyOptions({
            timeVisible: true,
            secondsVisible: true,
          });

          const newSeries = chart.addSeries(AreaSeries, { lineColor, topColor: areaTopColor, bottomColor: areaBottomColor });
          newSeries.setData(data);

          window.addEventListener('resize', handleResize);

          return () => {
              window.removeEventListener('resize', handleResize);

              chart.remove();
          };
      },
      [data, backgroundColor, lineColor, textColor, areaTopColor, areaBottomColor]
  );

  return (
    <div className='border border-white rounded-md overflow-hidden px-5 py-5'>
      <div
        ref={chartContainerRef}
      />
    </div>
  );
};

// Client/src/app/shared/components/chart/chart.component.ts
  import { Component, input, AfterViewInit, signal, viewChild, ElementRef, OnChanges } from '@angular/core';
  import { AreaSeries, createChart, ColorType } from 'lightweight-charts';
  import { DataPoint } from '../../interface/interface';

  @Component({
    selector: 'app-chart',
    imports: [],
    templateUrl: './chart.component.html',
    styleUrl: './chart.component.css'
  })
  export class ChartComponent implements OnChanges, AfterViewInit {
    data = input.required<DataPoint[]>();
    newSeries = signal<any>(null);
    chartContainerRef = viewChild<ElementRef<HTMLDivElement>>('chartContainerRef');
    colors = signal({
      backgroundColor : '#0a0b0b',
      lineColor : '#2962FF',
      textColor : 'white',
      areaTopColor : '#2962FF',
      areaBottomColor : 'rgba(41, 98, 255, 0.28)'
    });

    ngOnChanges() {
      this.newSeries().setData(this.data());
    }

    ngAfterViewInit(): void {
      this.setupChart();
    }

    private setupChart() {
      const container = this.chartContainerRef()?.nativeElement;
      if (!container){
        return;
      }
      const chart = createChart(container, {
        layout: {
            background: { type: ColorType.Solid, color: this.colors().backgroundColor },
            textColor: this.colors().textColor,
        },
        width: container.clientWidth,
        height: 300,
        grid: {
          vertLines: {
            color: 'transparent',
          },
          horzLines: {
            color: 'transparent',
          },
        },
      });
      chart.timeScale().fitContent();
      chart.timeScale().applyOptions({
        timeVisible: true,
        secondsVisible: true,
      });

      this.newSeries.set(chart.addSeries(AreaSeries, { 
        lineColor: this.colors().lineColor, 
        topColor: this.colors().areaTopColor, 
        bottomColor: this.colors().areaBottomColor 
      }));
      this.newSeries().setData(this.data());
    }
  }

<div class='border border-white rounded-md overflow-hidden px-5 py-5'>
    <div #chartContainerRef>
    </div>
</div>
