// Client/src/app/shared/components/floating-bar/floating-bar.component.ts
import { Component } from '@angular/core';
import { Router, RouterLink } from '@angular/router';

@Component({
  selector: 'app-floating-bar',
  imports: [RouterLink],
  templateUrl: './floating-bar.component.html',
  styleUrl: './floating-bar.component.css'
})
export class FloatingBarComponent {
  constructor(
    private router: Router
  ) {}

  openEventList(myEvents: boolean) {
    this.router.navigate(['/home'], {
      queryParams: {
        myEvents
      },
    });
  }
}

<div class="flex gap-3 rounded-sm fixed bottom-5 left-10 bg-secondary py-3 px-3">
    <div routerLink="/home/manageEvent">
        <button class="button-white">Create Event</button>
    </div>
    <div (click)="openEventList(true)">
        <button class="button-white">My Events</button>
    </div>
    <div (click)="openEventList(false)">
        <button class="button-white">All Events</button>
    </div>
    <div routerLink="/home/balance">
        <button class="button-white">Balance</button>
    </div>
</div>

// Client/src/components/FloatingBar.tsx
import { Link } from 'react-router-dom';
export default function FloatingBar() {
    return <div className="flex gap-3 rounded-sm fixed bottom-5 left-10 bg-secondary py-3 px-3">
        <Link to='/home/createEvent'>
            <button className="button-white">Create Event</button>
        </Link>
        <Link to='/home'>
            <button className="button-white">All Events</button>
    </Link>
        <Link to='/home/payment'>
            <button className="button-white">Balance</button>
        </Link>
    </div>
}
