// Client/src/app/shared/components/header/header.component.ts
import { Component, OnInit, signal } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService, User } from '@auth0/auth0-angular';

@Component({
  selector: 'app-header',
  imports: [],
  templateUrl: './header.component.html',
  styleUrl: './header.component.css'
})
export class HeaderComponent implements OnInit {
  user = signal<User | null>(null);
  isLoggedIn = signal<boolean>(false);

  constructor(
    private auth: AuthService,
    private router: Router
  ) {}

  ngOnInit() {
    const segments = this.router.url.split('/').filter(Boolean);
    const lastSegment = segments.at(-1);
  
    if (lastSegment) {
      this.isLoggedIn.set(true);
    }
    this.auth.user$.subscribe(user => {
      if (user) {
        this.user.set(user);
      }
    });
  }

  login() {
    this.auth.loginWithRedirect();
  }

  logout() {
    this.auth.logout();
  }
}

<div class='flex justify-between px-10 py-5'>
    <div class='flex flex-col justify-center text-xl font-bold '>
        Hypestock
    </div>
    <div>
        @if (user() && isLoggedIn()) {
            <div class="flex gap-8 items-center">
                <div>
                    {{user()?.name}}
                </div>
                <button (click)="logout()" type="button" class='button'>
                    Log Out
                </button> 
            </div>
        }
        @else {
            <button (click)="login()" class='button'>
                Log In
            </button>
        }
    </div>
</div>

// Client/src/components/Header.tsx
import { useAuth0 } from "@auth0/auth0-react";
import { useEffect, useState } from "react";

export default function Header() {
  const { logout, isAuthenticated, user, loginWithRedirect } = useAuth0();
  const [name, setName] = useState<string>();
  const [loggedIn, setLoggedIn] = useState(false);
  
  useEffect(() => {
    if (isAuthenticated){
      setName(user?.name!);
    }
  }, [isAuthenticated]);

  function handleLoginClick() {
    setLoggedIn(true);
    loginWithRedirect();
  }

  return (
    <div className='flex justify-between px-10 py-5'>
      <div className='flex flex-col justify-center text-xl font-bold text-[#EEEEEE]'>
        Hypestock
      </div>
      <div>
        {
          isAuthenticated && loggedIn ?
          <div className="flex gap-8 items-center">
            <div>
              {name}
            </div>
            <button onClick={() => logout()} className='button'>
              Log Out
            </button> 
          </div> :
          <button onClick={handleLoginClick} className='button'>
            Log In
          </button>
        }
      </div>
    </div>
  )
}
