// Client/src/pages/Trade.tsx
import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import type { Event } from "./AllEvents";
import convertTo12hFormat from "../utility/utility";
import api from "../api/axios";
import { connect, disconnect, isConnected } from "../lib/socket";
import OrderBook from "./OrderBook";
import LiveChart from "./LiveChart";
import PlaceOrder from "./PlaceOrder";

export default function Trade() {
    const { id } = useParams();
    const [event, setEvent] = useState<Event | null>(null);

    useEffect(() => {
        api.get<{event: Event | null}>('/event', {
            params:{
                id
            }
        })
        .then(({data}) => {
            setEvent(data.event);
            if (data.event){
                connectSocket(data.event.id);
            }
        })
        .catch(error => {
            console.log(error);
        });

        return () => {
            if (isConnected()){
                disconnect();
            }
        }
    }, []);

    function connectSocket(eventId: string) {
        connect(eventId);
    }

    return (
        <div className="grid grid-cols-1 gap-5">
            {
                event && 
                <>
                    <div className="p-8 px-8 bg-secondary rounded-sm flex justify-between">
                        <div className="flex flex-col gap-3">
                            <div className="font-bold text-xl">
                                {event?.title} <span className="ml-2 bg-blue-600 px-1 py-[2px] rounded-sm text-[10px]">{event?.category.toUpperCase()}</span>
                            </div>
                            <div>
                                {event?.description}
                            </div>
                        </div>
                        <div className="flex flex-col gap-3 items-end">
                            <div className="font-bold">
                                {event?.date}
                            </div>
                            <div>
                                {convertTo12hFormat(event?.startTime!)} - {convertTo12hFormat(event?.endTime!)}
                            </div>
                        </div>
                    </div>
                    <div className="grid grid-cols-12 gap-10">
                        <div className="col-span-4">
                            <PlaceOrder eventId={event?.id}></PlaceOrder>
                            <OrderBook></OrderBook>
                        </div>
                        <div className="col-span-8">
                            <LiveChart eventId={event?.id}/>
                        </div>
                    </div>
                </>
            }
      </div>
    );
}

// Client/src/app/feature/components/trading/trade/trade.component.ts
import { TitleCasePipe } from '@angular/common';
import { Component, OnDestroy, OnInit, signal } from '@angular/core';
import convertTo12hFormat from '../../../../shared/utility/time';
import { EventService } from '../../../services/event.service';
import { ActivatedRoute, Router } from '@angular/router';
import { Event } from '../../../../shared/interface/interface';
import { PlaceOrderComponent } from "../place-order/place-order.component";
import { OrderBookComponent } from "../order-book/order-book.component";
import { LiveChartComponent } from "../live-chart/live-chart.component";
import { Subscription } from 'rxjs';
import { SocketService } from '../../../../core/services/socket.service';

@Component({
  selector: 'app-trade',
  imports: [
    TitleCasePipe,
    PlaceOrderComponent,
    OrderBookComponent,
    LiveChartComponent
],
  templateUrl: './trade.component.html',
  styleUrl: './trade.component.css'
})
export class TradeComponent implements OnInit, OnDestroy {
  private subscription = new Subscription();
  event = signal<Event | null>(null);

  constructor(
    private eventService: EventService,
    private route: ActivatedRoute,
    private router: Router,
    private socket: SocketService
  ) {}

  ngOnInit(): void {
    this.route.queryParamMap.subscribe(params => {
      if (params && params.get('id')) {
        this.eventService.getEvent(
          params.get('id')!
        )
        .subscribe(({ event }) => {
          this.event.set(event);
        });
        this.socket.connect(params.get('id')!);
      }
      else {
        this.router.navigate(['notFound']);
      }
    });
  }

  convertTo12hFormat(time: string) {
    return convertTo12hFormat(time);
  }

  ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }
}

<div class="p-8 px-8 bg-secondary rounded-sm flex justify-between">
    @if (event()) {
        <div class="flex flex-col gap-3">
            <div class="font-bold text-xl">
                {{ event()?.title }} <span class="ml-2 bg-blue-600 px-1 py-[2px] rounded-sm text-[10px]">{{ event()?.category | titlecase }}</span>
            </div>
            <div>
                {{ event()?.description }}
            </div>
        </div>
        <div class="flex flex-col gap-3 items-end">
            <div class="font-bold">
                {{ event()?.date }}
            </div>
            <div>
                {{ convertTo12hFormat(event()?.startTime!) }} - {{ convertTo12hFormat(event()?.endTime!) }}
            </div>
        </div>
    }

</div>
<div class="grid grid-cols-12 gap-10 mt-10">
    <div class="col-span-4">
        <app-place-order [eventId]="event()?.id!" />
        <app-order-book [eventId]="event()?.id!" />
    </div>
    <div class="col-span-8">
        <app-live-chart [eventId]="event()?.id!" />
    </div>
</div>
